version: '3.8'

services:
  app:
    image: todo-front-dev
    ports:
      - 3001:3000
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      REACT_APP_BACKEND_URL: //localhost:3000
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
