version: '3.8'

services:
  app:
    image: bloglist-frontend-dev
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    environment: 
      DANGEROUSLY_DISABLE_HOST_CHECK: true
  server:
    image: bloglist-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file: .env
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-app-reverse-proxy
    depends_on:
      - app
      - server
