version: '3.8'

services:
  app:
    image: bloglist-frontend-prod
    build: 
      context: ./frontend
      dockerfile: Dockerfile
  server:
    image: bloglist-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-app-reverse-proxy-prod
    depends_on:
      - app
      - server
